title:            Python, Technology and other Random Bits™
description:      Blog.
url:              # Site url.
signoff:          Ducky
disqus_shortname: duckyblog
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-42115942-1

links:
  - name:         Twitter
    url:          http://twitter.com/ducky427
    external:     true
  - name:         GitHub
    url:          http://github.com/ducky427
    external:     true
  - name:         Blog
    url:          http://blog.ducky.io
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
